#!/usr/bin/env python
"""Regenerate docs/TOOLS.md from the server's live tool schemas.

Hand-written tool docs rot the moment a parameter changes. This reads what the
server actually advertises over MCP, so the reference can only ever be wrong if
the code is.

    python scripts/generate_tool_docs.py
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from nodriver_mcp.multiplexer import (  # noqa: E402
    _LIST_BROWSERS,
    _SHUTDOWN_BROWSER,
    list_tools as client_tools,
)
from nodriver_mcp.server import mcp  # noqa: E402

# Grouping mirrors the README table so the two never tell different stories.
CATEGORIES: list[tuple[str, list[str]]] = [
    ("Several browsers", [_LIST_BROWSERS.name, _SHUTDOWN_BROWSER.name]),
    ("Input automation", [
        "click", "click_at", "hover", "fill", "fill_form", "set_checked",
        "select_option", "type_text",
        "press_key", "drag", "upload_file", "handle_dialog",
    ]),
    ("Navigation & pages", [
        "navigate_page", "new_page", "list_pages", "select_page", "close_page",
        "close_browser", "wait_for", "wait_for_selector", "scroll_page",
        "scroll_to_selector", "resize_page",
    ]),
    ("Reading the page", [
        "take_snapshot", "take_screenshot", "get_page_content", "query_selector", "list_frames",
        "evaluate_script", "get_computed_styles", "save_pdf",
    ]),
    ("Network & console", [
        "list_network_requests", "get_network_request", "block_resources",
        "list_console_messages", "get_console_message",
        "enable_console_collection", "disable_console_collection",
    ]),
    ("Emulation", ["emulate", "emulate_device", "reset_emulation"]),
    ("Performance", [
        "performance_start_trace", "performance_stop_trace", "take_memory_snapshot",
    ]),
    ("Cookies & storage", [
        "get_cookies", "set_cookie", "clear_cookies", "get_local_storage",
        "set_local_storage",
    ]),
    ("Sessions", ["save_session", "load_session", "list_sessions"]),
    ("Profiles & browser", [
        "list_profiles", "create_profile", "use_profile", "use_temp_profile",
        "use_running_browser", "delete_profile", "set_browser_flags",
        "manage_extensions",
    ]),
    ("Anti-detection helpers", ["cf_verify", "bypass_insecure_warning"]),
]


def _type_of(spec: dict) -> str:
    """Render a JSON-Schema node as a short, readable type."""
    if "enum" in spec:
        return " \\| ".join(f"`{v}`" if v != "" else '`""`' for v in spec["enum"])
    if "$ref" in spec:
        return f"`{spec['$ref'].rsplit('/', 1)[-1]}`"
    if "anyOf" in spec:
        parts = [_type_of(s) for s in spec["anyOf"] if s.get("type") != "null"]
        return " \\| ".join(dict.fromkeys(parts)) or "`any`"
    kind = spec.get("type")
    if kind == "array":
        return f"array of {_type_of(spec.get('items', {}))}"
    if kind == "integer":
        return "`integer`"
    if kind == "object":
        return "`object`"
    return f"`{kind}`" if kind else "`any`"


def _bounds(spec: dict) -> str:
    out = []
    for key, label in (
        ("minimum", "min"), ("maximum", "max"),
        ("exclusiveMinimum", "> "), ("minItems", "min items"),
    ):
        if key in spec:
            out.append(f"{label} {spec[key]}".replace(">  ", "> "))
    return f" ({', '.join(out)})" if out else ""


def _hints(tool) -> str:
    ann = tool.annotations
    if not ann:
        return ""
    flags = []
    if ann.readOnlyHint:
        flags.append("read-only")
    if ann.destructiveHint:
        flags.append("destructive")
    if ann.idempotentHint:
        flags.append("idempotent")
    return f"  \n<sub>{' · '.join(flags)}</sub>" if flags else ""


def render(tools) -> str:
    by_name = {t.name: t for t in tools}
    seen: set[str] = set()
    lines: list[str] = [
        "# Tool reference",
        "",
        f"All {len(tools)} tools exposed by `nodriver-mcp`, with the exact parameters "
        "the server advertises over MCP.",
        "",
        "> Generated by `scripts/generate_tool_docs.py` — do not edit by hand.",
        "",
        "Every parameter carries a description in the schema itself, and values with a "
        "fixed set of options are constrained as enums, so an agent cannot invent one.",
        "",
        "## Contents",
        "",
    ]
    for title, names in CATEGORIES:
        anchor = title.lower().replace(" & ", "--").replace(" ", "-")
        lines.append(f"- [{title}](#{anchor}) ({len(names)})")
    lines.append("")

    for title, names in CATEGORIES:
        lines += [f"## {title}", ""]
        for name in names:
            tool = by_name.get(name)
            if tool is None:
                raise SystemExit(f"docs list an unknown tool: {name}")
            seen.add(name)
            schema = tool.inputSchema or {}
            props = schema.get("properties", {})
            required = set(schema.get("required", []))

            lines += [f"### `{name}`", ""]
            lines.append((tool.description or "").strip() + _hints(tool))
            lines.append("")
            if props:
                lines += [
                    "| Parameter | Type | Required | Description |",
                    "|---|---|---|---|",
                ]
                for pname, spec in props.items():
                    desc = " ".join((spec.get("description") or "").split())
                    desc = desc.replace("|", "\\|")
                    req = "yes" if pname in required else "—"
                    default = spec.get("default")
                    if pname not in required and default not in (None, ""):
                        # JSON spelling, not Python's — this documents a wire format.
                        shown = {True: "true", False: "false"}.get(default, default)
                        desc += f" *(default: `{shown}`)*"
                    lines.append(
                        f"| `{pname}` | {_type_of(spec)}{_bounds(spec)} | {req} | {desc} |"
                    )
            else:
                lines.append("*Takes no parameters.*")
            lines.append("")

    missing = sorted(set(by_name) - seen)
    if missing:
        raise SystemExit(f"tools missing from the docs categories: {missing}")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    tools = asyncio.run(client_tools())
    out = ROOT / "docs" / "TOOLS.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text(render(tools), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
